version: '3.8'

services:
  db:
    image: mariadb:lts
    container_name: kantin_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: kantin-cermat-dubes-12
      MYSQL_DATABASE: kantin_db
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  api:
    build: .
    container_name: kantin_api
    restart: always
    depends_on:
      - db
    ports:
      - "3005:3000"
    environment:
      - DATABASE_HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=kantin-cermat-dubes-12
      - DATABASE_NAME=kantin_db
      - JWT_SECRET=rahasia-negara-dubescermat-2026
      - JWT_REFRESH_SECRET=rahasia-refresh-dubescermat-2026
    volumes:
      - api_uploads:/app/uploads
    command: node dist/main.js

  web_admin:
    build: ../frontend
    container_name: kantin_web_admin
    restart: always
    ports:
      - "3006:80"

volumes:
  mariadb_data:
  api_uploads:
